# Options: https://prettier.io/docs/en/options.html

singleAttributePerLine: true
printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: true
arrowParens: avoid
htmlWhitespaceSensitivity: css
endOfLine: lf